name: Build RyCorne Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      # Specify the board and shield matrix for RyCorne (42-key Corne on nice_nano)
      board: '["nice_nano"]'
      shield: '["corne_left", "corne_right"]'
      # Use default Miryoku settings unless overridden by custom_config.h or rycorne.conf
      alphas: '["default"]'
      nav: '["default"]'
      layers: '["default"]'
      mapping: '["default"]'
      # Point to your custom config and keymap/conf files
      custom_config: '["#include \\"custom_config.h\\""]'
      kconfig: '["CONFIG_ZMK_CONFIG=\\"/github/workspace/config\\""]'
      # Add any specific branches or modules if needed, otherwise leave default
      # branches: '["default"]'
      # modules: '["default"]' 