name: Build RyCorne Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      # Specify the board and shield matrix for RyCorne (42-key Corne on nice_nano)
      board: '["nice_nano"]'
      shield: '["corne_left", "corne_right"]'
      # Use default Miryoku settings unless overridden by custom_config.h or the automatically found corne.conf
      alphas: '["default"]'
      nav: '["default"]'
      layers: '["default"]'
      mapping: '["default"]'
      # Use default for custom_config, as custom_config.h is included by corne.keymap
      custom_config: '["default"]'
      # Use default for kconfig, letting the build find config/corne.conf automatically
      kconfig: '["default"]'
      # Add any specific branches or modules if needed, otherwise leave default
      # branches: '["default"]'
      # modules: '["default"]' 