name: Build Corne Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      # Specify the board and shield matrix for Corne (42-key Corne on nice_nano with nice!view)
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view", "corne_right nice_view_adapter nice_view"]'
      # Use default Miryoku settings + custom_config.h included via corne.keymap + config/corne.conf
      alphas: '["default"]'
      nav: '["default"]'
      layers: '["default"]'
      mapping: '["default"]'
      custom_config: '["default"]' # Let main.yml use its default logic, custom_config.h is included by corne.keymap
      kconfig: '["default"]' # Let the build find config/corne.conf automatically
      # Add any specific branches or modules if needed, otherwise leave default
      # branches: '["default"]'
      # modules: '["default"]' 